In [13]:
import pandas as pd
import random
import string
import numpy as np

In [6]:
pd.DataFrame(
{"a" : [4 ,5, 6],
"b" : [7, 8, 9],
"c" : [10, 11, 12]},
index = [1, 2, 3])

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [7]:
def id():
    return ''.join(random.choice(string.ascii_letters) for i in range(5))

In [12]:
id()

'leQXs'

In [11]:
id()

'TtirT'

In [14]:
def score():
    return np.random.randint(0,100)

In [15]:
score()

23

In [20]:
pd.DataFrame({"국어": [score()],"영어": [score()], "수학": [score()], "사회": [score()], "과학": [score()]}, index=["qwert"])

       국어  영어  수학  사회  과학
qwert  86  68  94   4  51

In [46]:
pd.DataFrame({"국어": [score() for i in range (1,11)],"영어": [score() for i in range (1,11)], "수학": [score() for i in range (1,11)], "사회": [score() for i in range (1,11)], "과학": [score() for i in range (1,11)]}, index=[[id() for i in range(1,11)]])

       국어  영어  수학  사회  과학
exdYD  86  53  74  53  78
OytFq  25  52  76  28  16
ghtrK  71  49  66   6  63
ORoSX  17  74   8  17  24
Ekhjt  74  97  84  41  96
KdrIu  98  13  63  43   9
GtZFC  54  37   7  55  26
ERbud   8  59  27  50  95
YyszN  23  74   5  58  93
JItUe  52  13  29  71  72

In [43]:
pd.DataFrame([[score() for i in range(1,6)] for i in range(1,11)], index=[id() for i in range(1,11)], columns=['국어', '영어', '수학', '과학', '사회'])

       국어  영어  수학  과학  사회
wkEjz  98  42  20  45  26
EinWo  13  34  51  12  87
bJYSx  82   9  24  66  67
lnBwp  40  97   2  97  37
GgiNd  30  76  44  72  53
ufYwl  34   5   0  18  15
TrENb  90   8  18  90   2
cXGKE  68   8  23  34  13
DBZIy  16   5  58  79  76
zbUgp  56  73  54  90  51